version: '3'
services:
  
  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: 'bitnami/kafka:2.8.1'
    restart: always
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_NUM_PARTITIONS: 2
    ports:
      - 9092:9092

  database:
    image: bitnami/postgresql:12.10.0
    container_name: db-tarea2
    volumes:
      - './db/data:/bitnami/postgresql'
      - './db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro'
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: tarea2
    restart: always


  api: 
    build: ./api
    restart: always
    environment:
      
      kafkaHost: kafka:9092
    depends_on:
      - kafka
      - database
    ports:
      - 3000:3000

  stock: 
    build: ./rstock
    restart: always
    environment:
       kafkaHost: kafka:9092
    depends_on:
      - kafka
      - database
    ports:
      - 5000:3000

  location: 
    build: ./rubicacion
    restart: always
    environment:
       kafkaHost: kafka:9092
    depends_on:
      - kafka
      - database
    ports:
      - 4000:3000
  
  sale: 
    build: ./rventa
    restart: always
    environment:
       kafkaHost: kafka:9092
    depends_on:
      - kafka
      - database
    ports:
      - 6000:3000

